### ISSUE TITLE
组件报错，无法跑起来

### ISSUE THREAD

**Issue by shunqin-yu** [rsuite/document-nav#2]
按照示例中的例子都跑不起来，不知道是什么原因，还是说在后来的迭代中用法改变了而示例说明没有更新?

**Comment by zmhawk** [comment]
你好，不知你遇到的是什么错误，刚刚修复了一个 `Nav.Item` 引用错误的 bug，看看是否解决了你的问题

**Comment by shunqin-yu** [comment]
> 你好，不知你遇到的是什么错误，刚刚修复了一个`Nav.Item`引用错误的bug，看看是否解决了你的问题
> 
> @ rsuite /文档导航@ 1.0.1

太感谢了，现在已经可以正常跑起来了
